services:
  postgres:
    image: postgres:latest
    container_name: gibdd-db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: gibdd
    ports:
      - "5202:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: